account/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

event_rooms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import DetailView

from main import models
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('', views.index, name='index'),
    path('rooms/', views.FilterListView.as_view(model=models.Room), name='room_list'),
    path('room/<int:pk>/', DetailView.as_view(model=models.Room), name='room_detail'),
    path('events/', views.FilterListView.as_view(model=models.Event), name='event_list'),
    path('event/<int:pk>/', DetailView.as_view(model=models.Event), name='event_detail'),
    path('hotels/', views.FilterListView.as_view(model=models.Hotel), name='hotel_list'),
    path('hotel/<int:pk>/', DetailView.as_view(model=models.Hotel), name='hotel_detail'),
    path('persons/', views.FilterListView.as_view(model=models.Person), name='person_list'),
    path('person/<int:pk>/', DetailView.as_view(model=models.Person), name='person_detail'),
    path('searches/', views.FilterListView.as_view(model=models.RoomSearch), name='roomsearch_list'),
    path('search/<int:pk>/', DetailView.as_view(model=models.RoomSearch), name='roomsearch_detail'),
    path('invite/<int:room>/<int:search>/', views.create_invite, name='invite_create'),
    path('invite/<str:key>/', views.accept_invite, name='invite_accept'),
    path('request/<int:room>/<int:search>/', views.create_request, name='request_create'),
    path('request/<str:key>/', views.accept_request, name='request_accept'),
    path('create/room/<int:hotel_id>/', views.CreateRoomView.as_view(), name='room_create'),
    path('create/roomsearch/<int:event_id>/', views.CreateRoomSearchView.as_view(), name='roomsearch_create'),
    path('create/event/', views.CreateEventView.as_view(), name='event_create'),
    path('create/hotel/<int:event_id>/', views.CreateHotelView.as_view(), name='hotel_create'),
    path('create/person/', views.CreatePersonView.as_view(), name='person_create'),
    path('edit/person/<int:person_id>/', views.EditPersonView.as_view(), name='person_edit'),
    path('discord/', views.discord, name='discord'),
    path('template/<path:path>', views.debug, name='debug'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import hashlib
import base64

# Create your models here.


'''
@startuml
class Event
{
    +name: string
}

class Hotel
{
    +name: string
    +event: Event
}

class Room
{
    +hotel: Hotel
    +owner: Person
    +people: Person[]
    +maxPeople: int
    +description: string
    -preferredGender: Gender
}

class Person
{
    +name: string
    -gender: Gender
    +email: string
    +discord: string
    +description: string
    +user: User
}

class RoomSearch
{
    +event: Event
    +person: Person
    +description: string
}

RoomSearch --> Event
RoomSearch --> Person


enum Gender
{
    MALE
    FEMALE
    OTHER
    ANY
}



Hotel --> Event
Room --> Hotel
Room --> Person

Room --> Gender
Person --> Gender
@enduml
'''


class Event(models.Model):
    name = models.TextField()

    def __str__(self):
        return self.name


class Hotel(models.Model):
    name = models.TextField()
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.event} {self.name}"


class Person(models.Model):
    name = models.TextField()
    email = models.TextField(default='', blank=True)
    discord = models.TextField(default='', blank=True)
    description = models.TextField(default='', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Room(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    owner = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='owned_rooms')
    people = models.ManyToManyField(Person, related_name='rooms')
    maxPeople = models.IntegerField()
    description = models.TextField(default='', blank=True)

    def _get_is_full(self):
        return self.people.count() >= self.maxPeople

    is_full = property(_get_is_full)

    def __str__(self):
        return f"{self.owner.name}'s room at {self.hotel}"


class RoomSearch(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    description = models.TextField(default='', blank=True)

    def __str__(self):
        return f"Room Search from {self.person} for {self.event}"


class RoomInvite(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    search = models.ForeignKey(RoomSearch, on_delete=models.CASCADE)
    _key = models.TextField(unique=True)

    def get_key(self):
        m = hashlib.sha256()
        m.update(bytes(self.id))
        key = base64.urlsafe_b64encode(m.digest()).decode('utf-8')
        self._key = key
        self.save()
        return key

    key = property(get_key)

    def __str__(self):
        return f"Invite {self.search.person} to {self.room}"


class RoomRequest(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    search = models.ForeignKey(RoomSearch, on_delete=models.CASCADE)
    _key = models.TextField(unique=True)

    def get_key(self):
        m = hashlib.sha256()
        m.update(bytes(self.id))
        key = base64.urlsafe_b64encode(m.digest()).decode('utf-8')
        self._key = key
        self.save()
        return key

    key = property(get_key)

    def __str__(self):
        return f"Request {self.search.person} to join {self.room}"

main/forms.py
from django.forms import ModelForm, widgets

from . import models


class RoomSearchCreationForm(ModelForm):
    class Meta:
        model = models.RoomSearch
        fields = ['event', 'person', 'description']


class RoomCreationForm(ModelForm):
    class Meta:
        model = models.Room
        fields = ['hotel', 'owner', 'maxPeople', 'description']


class EventCreationForm(ModelForm):
    class Meta:
        model = models.Event
        fields = ['name']
        widgets = {'name': widgets.TextInput}


class HotelCreationForm(ModelForm):
    class Meta:
        model = models.Hotel
        fields = ['name', 'event']
        widgets = {'name': widgets.TextInput}


class PersonForm(ModelForm):
    class Meta:
        model = models.Person
        fields = ['name', 'email', 'discord', 'description']
        widgets = {'name': widgets.TextInput, 'email': widgets.TextInput, 'discord': widgets.TextInput}

main/views.py
import re

from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.views.generic import ListView

from account.account_util import is_moderator, manages
from . import models, forms


def unauthorized():
    return HttpResponse("unauthorized", status=401)  # TODO render proper error page


# Create your views here.

def index(request):
    return render(request, 'index.html')


class FilterListView(ListView):
    def get_queryset(self):
        queryset = super().get_queryset()
        filter = {}
        for key in self.request.GET:
            key = str(key)
            # process key
            if key.startswith('Count__'):
                a, field, b = tuple(key.split('__'))
                kwargs = {f'{a}__{field}': models.models.Count(field)}
                queryset = queryset.annotate(**kwargs)
            # process value
            match = re.match(r'F\((?P<field>\w*)\)', self.request.GET[key])
            if match:
                field = match.group('field')
                filter[key] = models.models.F(field)
            else:
                filter[key] = self.request.GET[key]
        queryset = queryset.filter(**filter)
        return queryset


def create_invite(request, room, search):
    invite = models.RoomInvite.objects.create(room=models.Room.objects.get(id=room),
                                              search=models.RoomSearch.objects.get(id=search))
    # TODO replace with send mail
    return HttpResponse(invite.key)


def create_request(request, room, search):
    room_request = models.RoomRequest.objects.create(room=models.Room.objects.get(id=room),
                                                     search=models.RoomSearch.objects.get(id=search))
    # TODO replace with send mail
    return HttpResponse(room_request.key)


def accept_invite(request, key):
    invite = models.RoomInvite.objects.get(_key=key)
    room = invite.room
    search = invite.search
    room.people.add(search.person)
    room.save()
    search.delete()
    invite.delete()
    return redirect(reverse('room_detail', kwargs={'pk': room.pk}))


def accept_request(request, key):
    room_request = models.RoomRequest.objects.get(_key=key)
    room = room_request.room
    search = room_request.search
    room.people.add(search.person)
    room.save()
    search.delete()
    room_request.delete()
    return redirect(reverse('room_detail', kwargs={'pk': room.pk}))


class CreateRoomSearchView(View):
    def get(self, request, event_id):
        form = forms.RoomSearchCreationForm(initial={'event': event_id})
        form.fields['person'].queryset = models.Person.objects.filter(user=request.user)
        return render(request, 'main/create.html', {'form': form, 'submit': 'Create Room Search'})

    def post(self, request, event_id):
        form = forms.RoomSearchCreationForm(request.POST)
        search = form.save()
        return redirect(reverse('roomsearch_detail', kwargs={'pk': search.pk}))


class CreateRoomView(View):
    def get(self, request, hotel_id):
        form = forms.RoomCreationForm(initial={'hotel': hotel_id})
        form.fields['owner'].queryset = models.Person.objects.filter(user=request.user)
        return render(request, 'main/create.html', {'form': form, 'submit': 'Create Room'})

    def post(self, request, hotel_id):
        form = forms.RoomCreationForm(request.POST)
        room = form.save()
        room.people.add(room.owner)
        room.save()
        return redirect(reverse('room_detail', kwargs={'pk': room.pk}))


class CreateEventView(View):
    def get(self, request):
        if not is_moderator(request.user):
            return unauthorized()
        form = forms.EventCreationForm()
        return render(request, 'main/create.html', {'form': form, 'submit': 'Create Event'})

    def post(self, request):
        if not is_moderator(request.user):
            return unauthorized()
        form = forms.EventCreationForm(request.POST)
        event = form.save()
        return redirect(reverse('event_detail', kwargs={'pk': event.pk}))


class CreateHotelView(View):
    def get(self, request, event_id):
        if not is_moderator(request.user):
            return unauthorized()
        form = forms.HotelCreationForm(initial={'event': event_id})
        return render(request, 'main/create.html', {'form': form, 'submit': 'Create Hotel'})

    def post(self, request, event_id):
        if not is_moderator(request.user):
            return unauthorized()
        form = forms.HotelCreationForm(request.POST)
        hotel = form.save()
        return redirect(reverse('hotel_detail', kwargs={'pk': hotel.pk}))


class CreatePersonView(View):
    def get(self, request):
        form = forms.PersonForm()
        return render(request, 'main/create.html', {'form': form, 'submit': 'Create Person'})

    def post(self, request):
        form = forms.PersonForm(request.POST)
        person = form.save(commit=False)
        person.user = request.user
        person.save()
        return redirect(reverse('person_detail', kwargs={'pk': person.pk}))


class EditPersonView(View):
    def get(self, request, person_id):
        person = models.Person.objects.get(pk=person_id)
        if not manages(request.user, person):
            return unauthorized()
        form = forms.PersonForm(instance=person)
        return render(request, 'main/create.html', {'form': form, 'submit': 'Edit Person'})

    def post(self, request, person_id):
        person = models.Person.objects.get(pk=person_id)
        if not manages(request.user, person):
            return unauthorized()
        form = forms.PersonForm(request.POST, instance=person)
        form.save()
        return redirect(reverse('person_detail', kwargs={'pk': person.pk}))


redirect_url = 'https://discordapp.com/api/oauth2/authorize?client_id=656727286003007498&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fdiscord&response_type=code&scope=identify'


def discord(request):
    if 'code' in request.GET:
        code = request.GET['code']
        return HttpResponse(code)
    return redirect(redirect_url)


def debug(request, path):
    return render(request, f'{path}.html')

templates/main/create.html
{% extends 'base.html' %}
{% load formutils %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|floating_label_form }}
        <input class="btn btn-primary" type="submit" value="{{ submit }}"/>
    </form>
{% endblock %}

templates/main/event_detail.html
{% extends "base.html" %}
{% load account %}

{% block content %}
    <h1>{{ event }}</h1>
    <div class="list-group">
        <a class="list-group-item list-group-item-action" href="{% url 'hotel_list' %}?event={{ event.id }}">Hotels</a>
        <a class="list-group-item list-group-item-action" href="{% url 'roomsearch_list' %}?event={{ event.id }}">Room
            Searches</a>
        <a class="list-group-item list-group-item-action" href="{% url 'room_list' %}?hotel__event={{ event.id }}">All
            Rooms</a>
    </div>

    {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'roomsearch_create' event.id %}">Create Room Search</a>
        {% if user|is_moderator %}
            <a class="btn btn-primary" href="{% url 'hotel_create' event.id %}">Create Hotel</a>
        {% endif %}
    {% endif %}
{% endblock %}

templates/main/event_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Events</h1>
    {% if event_list %}
        <div class="list-group">
            {% for event in event_list %}
                <a class="list-group-item list-group-item-action" href="{% url 'event_detail' event.id %}">{{ event }}</a>
            {% endfor %}
        </div>
    {% else %}
        <p>There are no events.</p>
    {% endif %}
{% endblock %}

templates/main/hotel_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ hotel }}</h1>
    <div class="list-group">
        <a class="list-group-item list-group-item-action" href="{% url 'room_list' %}?hotel={{ hotel.id }}">Rooms</a>
        <a class="list-group-item list-group-item-action"
           href="{% url 'event_detail' hotel.event.id %}">{{ hotel.event }}</a>
    </div>

    {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'room_create' hotel.id %}">Create Room</a>
    {% endif %}
{% endblock %}

templates/main/hotel_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Hotels</h1>
    {% if hotel_list %}
        <div class="list-group">
            {% for hotel in hotel_list %}
                <a class="list-group-item list-group-item-action" href="{% url 'hotel_detail' hotel.id %}">{{ hotel }}</a>
            {% endfor %}
        </div>
    {% else %}
        <p>There are no hotels.</p>
    {% endif %}
{% endblock %}

templates/main/person_detail.html
{% extends "base.html" %}

{% load account %}

{% block content %}
    <h1>{{ person }}</h1>
    <div class="list-group">
        {% if person.name %}
            <div class="list-group-item">{{ person.name }}</div>
        {% endif %}
        {% if person.email %}
            <a class="list-group-item list-group-item-action" href="mailto:{{ person.email }}">{{ person.email }}</a>
        {% endif %}
        {% if person.discord %}
            <div class="list-group-item">{{ person.discord }}</div>
        {% endif %}
        {% if person.description %}
            <div class="list-group-item">{{ person.description }}</div>
        {% endif %}
    </div>

    {% if user|manages:person %}
        <a class="btn btn-primary" href="{% url 'person_edit' person.id%}">Edit</a>
    {% endif %}

{% endblock %}

templates/main/person_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Persons</h1>
    {% if person_list %}
        <div class="list-group">
            {% for person in person_list %}
                <a class="list-group-item list-group-item-action" href="{% url 'person_detail' person.id %}">{{ person }}</a>
            {% endfor %}
        </div>
    {% else %}
        <p>There are no persons.</p>
    {% endif %}
{% endblock %}

templates/main/room_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ room }}</h1>
    <div class="list-group">
        <a href="{% url "hotel_detail" room.hotel.id %}"
           class="list-group-item list-group-item-action">{{ room.hotel }}</a>
        <a href="{% url 'person_detail' room.owner.id %}"
           class="list-group-item list-group-item-action">{{ room.owner }}</a>
        <a href="{% url 'person_list' %}?rooms={{ room.id }}" class="list-group-item list-group-item-action">
            <span class="badge
{% if room.is_full %}badge-danger{% else %}badge-primary{% endif %}
badge-pill">{{ room.people.count }}/{{ room.maxPeople }}</span> people
        </a>
    </div>

    {% if not room.is_full %}
        {% for person in user.person_set.all %}
            {% for search in person.roomsearch_set.all %}
                {% if search.event == room.hotel.event %}
                    <form action="{% url 'request_create' room.id search.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary" value="Request join {{ search.person }}"/>
                    </form>
                {% endif %}
            {% endfor %}
        {% endfor %}
    {% endif %}

{% endblock %}

templates/main/room_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Rooms</h1>
    {% if room_list %}
        {% if not "Count__people__lt" in request.GET %}
            <form method="get" action="{{ request.get_full_path }}">
                {% for key, value in request.GET.items %}
                    <input type="hidden" name="{{ key }}" value="{{ value }}"/>
                {% endfor %}
                <input type="hidden" name="Count__people__lt" value="F(maxPeople)"/>
                <input class="btn btn-primary" type="submit" value="Filter full rooms"/>
            </form>
        {% else %}
            <form method="get" action="{{ request.get_full_path }}">
                {% for key, value in request.GET.items %}
                    {% if key != "Count__people__lt" %}
                        <input type="hidden" name="{{ key }}" value="{{ value }}"/>
                    {% endif %}
                {% endfor %}
                <input class="btn btn-primary" type="submit" value="List all rooms"/>
            </form>
        {% endif %}
        <div class="list-group">
            {% for room in room_list %}
                <a class="list-group-item list-group-item-action" href="{% url 'room_detail' room.id %}">{{ room }}</a>
            {% endfor %}
        </div>
    {% else %}
        <p>There are no rooms.</p>
    {% endif %}
{% endblock %}

templates/main/roomsearch_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ roomsearch }}</h1>
    <div class="list-group">
        <a href="{% url 'person_detail' roomsearch.person.id %}"
           class="list-group-item list-group-item-action">{{ roomsearch.person }}</a>
        <a href="{% url 'event_detail' roomsearch.event.id %}"
           class="list-group-item list-group-item-action">{{ roomsearch.event }}</a>
        {% if roomsearch.description %}
            <div class="list-group-item">{{ roomsearch.description }}</div>
        {% endif %}
    </div>

    {% for person in user.person_set.all %}
        {% for room in person.owned_rooms.all %}
            {% if room.hotel.event == roomsearch.event and not room.is_full %}
                <form action="{% url 'invite_create' room.id roomsearch.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary" value="Invite to {{ room }}"/>
                </form>
            {% endif %}
        {% endfor %}
    {% endfor %}

{% endblock %}

templates/main/roomsearch_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Room Searches</h1>
    {% if roomsearch_list %}
        <div class="list-group">
            {% for roomsearch in roomsearch_list %}
                <a class="list-group-item list-group-item-action" href="{% url 'roomsearch_detail' roomsearch.id %}">{{ roomsearch }}</a>
            {% endfor %}
        </div>
    {% else %}
        <p>There are no room searches.</p>
    {% endif %}
{% endblock %}